((nil . ((indent-tabs-mode . t)
         (tab-width . 8)
         (fill-column . 80)))
 (java-mode . ((c-basic-offset . 8)
	       (whitespace-line-column . 100)))
 (sgml-mode . ((sgml-basic-offset . 8)
	       (whitespace-line-column . 100)))
 ; emacs complains about sgml-basic-offset being unsafe, so let's set it only for XML
 (emacs-lisp-mode . ((indent-tabs-mode . nil)))
)
